### ISSUE TITLE
[ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. 

### ISSUE THREAD

**Issue by TimWeidner** [rishabh3112/gridsome-plugin-pwa#19]
Hello there, I got following issue after npm installing this and adding to the config.

This is the result

```
Scaffolding PWA assets
 - manifest.json..TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.join (path.js:427:7)
    at createManifest (X:\_tim\vuetest\timweidner.de\node_modules\gridsome-plugin-pwa\files\manifest.js:17:38)
    at Plugin.api.afterBuild (X:\_tim\vuetest\timweidner.de\node_modules\gridsome-plugin-pwa\index.js:23:40)
    at Plugins.run (X:\_tim\vuetest\timweidner.de\node_modules\gridsome\lib\app\Plugins.js:141:17)
```

This is my config
```
module.exports = {
  siteName: "Tims Blog",
  siteDescription:
    "100% Meinung zu Filmen, Gitarren, Spielen, Cosplay und mehr",

  templates: {
    Post: "/:title",
    Tag: "/tag/:id"
  },

  plugins: [
    {
      // Create posts from markdown files
      use: "@gridsome/source-filesystem",
      options: {
        typeName: "Post",
        path: "content/posts/*.md",
        refs: {
          // Creates a GraphQL collection from 'tags' in front-matter and adds a reference.
          tags: {
            typeName: "Tag",
            create: true
          }
        }
      }
    },
    {
      use: "gridsome-plugin-pwa",
      options: {
        title: "Tims Blog",
        startUrl: "/",
        display: "standalone",
        statusBarStyle: "default",
        manifestPath: "manifest.json",
        serviceWorkerPath: "service-worker.js",
        cachedFileTypes: "js,json,css,html,png,jpg,jpeg,svg,webp,gif",
        shortName: "Tims Blog",
        themeColor: "#353b48",
        backgroundColor: "#2f3640",
        icon: "src/favicon.png", // must be provided
        msTileImage: "src/favicon.png",
        msTileColor: "#353b48"
      }
    }
  ],

  transformers: {
    //Add markdown support to all file-system sources
    remark: {
      externalLinksTarget: "_blank",
      externalLinksRel: ["nofollow", "noopener", "noreferrer"],
      anchorClassName: "icon icon-link",
      plugins: ["@gridsome/remark-prismjs"]
    }
  }
};
```

I did pretty much the same thing as 
https://github.com/rishabh3112/gridsome-plugin-pwa/issues/8#issuecomment-543806399

**Comment by camppacifictech** [comment]
The var name used in Gridsome config may have been updated - it's now 'outDir' instead of 'outputDir'. PR to fix it is above.

**Comment by TimWeidner** [comment]
> 
> 
> The var name used in Gridsome config may have been updated - it's now 'outDir' instead of 'outputDir'. PR to fix it is above.

I tested your PR and it is indeed working now.

I actually noticed the naming prior to posting the issue, but I did not try to modify the plugin files, I rather added an "outputDir" to my config, which did nothing.

**Comment by TimWeidner** [comment]
Oh, my bad, it most certainly seems like I am just plain stupid.
I was running gridsome v0.7.8 and outputDir was not refactored to outDir, it is the exact other way around. [On 15th of October outDir was refactored to outputDir](https://github.com/gridsome/gridsome/commit/2538985de723d3fb2db0f07aae63153e03f2e6e3). While this was updated everywhere else, it was not updated in the docs, which tricked me into thinking "outDir" is correct.
