### ISSUE TITLE
Build Failure Due to Sharp Library

### ISSUE THREAD

**Issue by RehanSaeed** [rishabh3112/gridsome-plugin-pwa#30]
When I run a `gridsome build`, I get:

```
Initializing plugins...
Error:
Something went wrong installing the "sharp" module

The specified procedure could not be found.
\\?\C:\GitHub\rehansaeed.github.io\node_modules\gridsome-plugin-pwa\node_modules\sharp\build\Release\sharp.node

- Remove the "node_modules/sharp" directory then run
  "npm install --ignore-scripts=false --verbose" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/install
- Search for this error at https://github.com/lovell/sharp/issues

    at Object.<anonymous> (C:\GitHub\rehansaeed.github.io\node_modules\gridsome-plugin-pwa\node_modules\sharp\lib\const
ructor.js:34:9)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\GitHub\rehansaeed.github.io\node_modules\gridsome-plugin-pwa\node_modules\sharp\lib\index
.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\GitHub\rehansaeed.github.io\node_modules\gridsome-plugin-pwa\files\manifest.js:12:37)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rehansaeed.com@1.0.0 build: `gridsome build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rehansaeed.com@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by rishabh3112** [comment]
@RehanSaeed I can't replicate the issue ( on Linux ). Please share a minimum reproducible repository.
This issue is also tends to be linked with `sharp` package, can you test if is it working on windows?

**Comment by damasdev** [comment]
I've same problem here:

`Initializing plugins...
Error: 
Something went wrong installing the "sharp" module

dlopen(/Volumes/HDD/website/myweb/node_modules/gridsome-plugin-pwa/node_modules/sharp/build/Release/sharp.node, 1): Library not loaded: @rpath/libvips-cpp.42.dylib
  Referenced from: /Volumes/HDD/website/myweb/node_modules/gridsome-plugin-pwa/node_modules/sharp/build/Release/sharp.node
  Reason: Incompatible library version: sharp.node requires version 55.0.0 or later, but libvips-cpp.42.dylib provides version 54.0.0

- Run "brew update && brew upgrade vips"
- Consult the installation documentation at https://sharp.pixelplumbing.com/install
- Search for this error at https://github.com/lovell/sharp/issues

    at Object.<anonymous> (/Volumes/HDD/website/myweb/node_modules/gridsome-plugin-pwa/node_modules/sharp/lib/constructor.js:34:9)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Volumes/HDD/website/myweb/node_modules/gridsome-plugin-pwa/node_modules/sharp/lib/index.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Volumes/HDD/website/myweb/node_modules/gridsome-plugin-pwa/files/manifest.js:12:37)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)`

**Comment by michaelpumo** [comment]
I'm not sure if it helps but I also get the following error:

```
> gridsome build

Gridsome v0.7.13

Initializing plugins...
Error:
Something went wrong installing the "sharp" module

dlopen(/Users/paranoidandroid/Documents/websites/michaelpumo/node_modules/gridsome-plugin-pwa/node_modules/sharp/build/Release/sharp.node, 1): Library not loaded: @rpath/libvips-cpp.42.dylib
  Referenced from: /Users/paranoidandroid/Documents/websites/michaelpumo/node_modules/gridsome-plugin-pwa/node_modules/sharp/build/Release/sharp.node
  Reason: Incompatible library version: sharp.node requires version 55.0.0 or later, but libvips-cpp.42.dylib provides version 54.0.0

- Run "brew update && brew upgrade vips"
- Consult the installation documentation at https://sharp.pixelplumbing.com/install
- Search for this error at https://github.com/lovell/sharp/issues

    at Object.<anonymous> (/Users/paranoidandroid/Documents/websites/michaelpumo/node_modules/gridsome-plugin-pwa/node_modules/sharp/lib/constructor.js:34:9)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/paranoidandroid/Documents/websites/michaelpumo/node_modules/gridsome-plugin-pwa/node_modules/sharp/lib/index.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
```

Machine: macOS Catalina.
NPM: 6.14.4
Gridsome PlugiN PWA: 0.0.14

The build also fails on my Netlify account so I'm not sure how dependent this is on environment.

My site (with the issue) is in a publicly accessible repo you can clone from **master**: https://github.com/michaelpumo/michaelpumo

Thanks!

**Comment by sir-red-dab** [comment]
I deleted `sharp` from the `node_modules` of this plugin. After doing that it worked fine.

**Comment by rishabh3112** [comment]
I still couldn't reproduce the issue on my machine. I have patched another version with sharp being updated to latest version.

I found this thread from `gatsby-plugin-manifest` which can be useful for you all.
If another version if sharp is installed in the system, this issue can be found there
> If updating these doesn’t fix the issue, your project probably uses other plugins from the community that depend on a different version of sharp. Try running npm list sharp or yarn why sharp to see all packages in the current project that use sharp and try updating them as well.

Reference:
https://www.gatsbyjs.org/packages/gatsby-plugin-manifest/

Hope this fixes the issue.

**Comment by brianshano** [comment]
Had same problem. 
`npm list sharp
tunesource-gridsome@ /Users/br20010034/src/pers/tunesource-gridsome
└─┬ gridsome@0.7.13
  └── UNMET DEPENDENCY sharp@0.23.4

npm ERR! missing: sharp@0.23.4, required by gridsome@0.7.13`

removing sharp from node_modules of this package allowed my code run again.

**Comment by RehanSaeed** [comment]
I have no globally installed npm modules, so other sharp instances is not the problem. I'm also on Windows, so we know it's failing on multiple operating systems.

**Comment by damasdev** [comment]
Hi everyone try to do this:

rm -rf node_modules
brew uninstall libvips
brew update
brew upgrade
brew cleanup

add this to the package.json:

`"resolutions": {
    "**/sharp": "^0.25.2"
  }`

yarn install

Hope this fix your issues, because it's work for me.

**Comment by michaelpumo** [comment]
> Hi everyone try to do this:
> 
> rm -rf node_modules
> brew uninstall libvips
> brew update
> brew upgrade
> brew cleanup
> 
> add this to the package.json:
> 
> `"resolutions": { "**/sharp": "^0.25.2" }`
> 
> yarn install
> 
> Hope this fix your issues, because it's work for me.

That may very well work but it’s not a solution because I have a site that builds on Netlify and we can’t simply run brew commands like that.

**Comment by jsappme** [comment]
same issue here

**Comment by damasdev** [comment]
> I had to **downgrade** in order to get a successful build:
> 
> `"gridsome-plugin-pwa": "0.0.13"`

Can you help me to solve this? When i build on netlify i got the same errors.

this is my settings:
`{
      use: 'gridsome-plugin-pwa',
      options: {
          title: "KodeDasar.com",
          startUrl: "/",
          display: "standalone",
          statusBarStyle: "default",
          manifestPath: "manifest.json",
          disableServiceWorker: true,
          serviceWorkerPath: "service-worker.js",
          cachedFileTypes: "js,json,css,html,png,jpg,jpeg,svg",
          shortName: "kodedasar",
          themeColor: "#666600",
          backgroundColor: "#ffffff",
          icon: "author-min.png", // must be provided like 'src/favicon.png'
          msTileImage: "",
          msTileColor: "#666600"
      }
    }`

Errors:

`Gridsome v0.7.13

Initializing plugins...
Load sources - 0.4s
Create GraphQL schema - 0.18s
Create pages and templates - 0.07s
Generate temporary code - 0.08s
Bootstrap finish - 4.5s
gridsome-plugin-manifest: 133.638ms
gridsome-plugin-service-worker: 2.213s
Compile assets - 9.68s
Execute GraphQL (42 queries) - 2.51s
Write out page data (42 files) - 0.04s
Render HTML (42 files) - 0.82s
Process files (0 files) - 0s
Process images (28 images) - 6.37s
Scaffolding PWA assets
 - manifest.json..Error: Input file is missing`

![build](https://user-images.githubusercontent.com/30591545/78952137-bed2f680-7afe-11ea-9a68-98de09a2a49a.png)

**Comment by michaelpumo** [comment]
> > I had to **downgrade** in order to get a successful build:
> > `"gridsome-plugin-pwa": "0.0.13"`
> 
> Can you help me to solve this? When i build on netlify i got the same errors.
> 
> this is my settings:
> `{ use: 'gridsome-plugin-pwa', options: { title: "KodeDasar.com", startUrl: "/", display: "standalone", statusBarStyle: "default", manifestPath: "manifest.json", disableServiceWorker: true, serviceWorkerPath: "service-worker.js", cachedFileTypes: "js,json,css,html,png,jpg,jpeg,svg", shortName: "kodedasar", themeColor: "#666600", backgroundColor: "#ffffff", icon: "author-min.png", // must be provided like 'src/favicon.png' msTileImage: "", msTileColor: "#666600" } }`
> 
> Errors:
> 
> `Gridsome v0.7.13
> 
> Initializing plugins...
> Load sources - 0.4s
> Create GraphQL schema - 0.18s
> Create pages and templates - 0.07s
> Generate temporary code - 0.08s
> Bootstrap finish - 4.5s
> gridsome-plugin-manifest: 133.638ms
> gridsome-plugin-service-worker: 2.213s
> Compile assets - 9.68s
> Execute GraphQL (42 queries) - 2.51s
> Write out page data (42 files) - 0.04s
> Render HTML (42 files) - 0.82s
> Process files (0 files) - 0s
> Process images (28 images) - 6.37s
> Scaffolding PWA assets
> 
> * manifest.json..Error: Input file is missing`
> 
> ![build](https://user-images.githubusercontent.com/30591545/78952137-bed2f680-7afe-11ea-9a68-98de09a2a49a.png)

Just downgrade this package in your package.json file. You probably have it set to 0.0.14 or 0.0.15...change it to as I showed above. 0.0.13. Delete node_modules and run npm install.

**Comment by rishabh3112** [comment]
So I found the problem, gridsome uses sharp and the versions of it in the plugin and gridsome are conflicting. This would be patched in the next patch release :)

**Comment by rishabh3112** [comment]
Done.

**Comment by RehanSaeed** [comment]
This now works. Thanks!

**Comment by douglassllc** [comment]
@RehanSaeed 

platform: macOS 10.15.3
node: v12.16.3
gridsome: 0.7.0

gridsome-plugin-pwa: version > 0.0.13 still caused the same build failure.

**Comment by jsappme** [comment]
gridsome-plugin-pwa: version > 0.0.10 still caused the same build failure.

`Scaffolding PWA assets
 - manifest.json..Error: Unsupported input '' of type string
    at Sharp._createInputDescriptor (/Users/herve76/Documents/GitHub/gridsomify/node_modules/sharp/lib/input.js:45:11)
    at new Sharp (/Users/herve76/Documents/GitHub/gridsomify/node_modules/sharp/lib/constructor.js:238:29)
    at Sharp (/Users/herve76/Documents/GitHub/gridsomify/node_modules/sharp/lib/constructor.js:116:12)
    at /Users/herve76/Documents/GitHub/gridsomify/node_modules/gridsome-plugin-pwa/files/manifest.js:46:31
    at Array.map (<anonymous>)
    at createManifest (/Users/herve76/Documents/GitHub/gridsomify/node_modules/gridsome-plugin-pwa/files/manifest.js:30:27)
    at /Users/herve76/Documents/GitHub/gridsomify/node_modules/gridsome-plugin-pwa/index.js:23:40
    at Plugins.run (/Users/herve76/Documents/GitHub/gridsomify/node_modules/gridsome/lib/app/Plugins.js:141:17)
    at async module.exports (/Users/herve76/Documents/GitHub/gridsomify/node_modules/gridsome/lib/build.js:41:3)
error Command failed with exit code 1.
`

**Comment by sir-red-dab** [comment]
> gridsome-plugin-pwa: version > 0.0.13 still caused the same build failure.
> 
> ```
> Scaffolding PWA assets
> 
> * manifest.json..Error: Unsupported input '' of type string
>   at Sharp._createInputDescriptor (/Users/herve76/Documents/GitHub/gridsomify/node_modules/sharp/lib/input.js:45:11)
>   at new Sharp (/Users/herve76/Documents/GitHub/gridsomify/node_modules/sharp/lib/constructor.js:238:29)
>   at Sharp (/Users/herve76/Documents/GitHub/gridsomify/node_modules/sharp/lib/constructor.js:116:12)
>   at /Users/herve76/Documents/GitHub/gridsomify/node_modules/gridsome-plugin-pwa/files/manifest.js:46:31
>   at Array.map ()
>   at createManifest (/Users/herve76/Documents/GitHub/gridsomify/node_modules/gridsome-plugin-pwa/files/manifest.js:30:27)
>   at /Users/herve76/Documents/GitHub/gridsomify/node_modules/gridsome-plugin-pwa/index.js:23:40
>   at Plugins.run (/Users/herve76/Documents/GitHub/gridsomify/node_modules/gridsome/lib/app/Plugins.js:141:17)
>   at async module.exports (/Users/herve76/Documents/GitHub/gridsomify/node_modules/gridsome/lib/build.js:41:3)
>   error Command failed with exit code 1.
>   ```

I see a different error... The error says `Unsupported input '' of type string`, so I think something is not configured right in your `gridsome.config.js` file. Try using `""` (double quotes) instead of `''` (single quotes)?

**Comment by cameronrr** [comment]
I am having this issue now in 0.0.18. Same as above two posts.
